# Data Collection

### CSV

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/us_indicators.csv')

In [3]:
df

,date,cpi,policy_rate,neer,money_supply,inflation_target,type_of_monetary_policy
0,31/1/2001,1.32,1.5,89.24,147.07,inrange,ease
1,28/2/2001,1.44,1.5,90.47,145.49,inrange,ease
2,31/3/2001,1.44,1.5,89.33,140.02,inrange,ease
3,30/4/2001,2.52,1.5,87.32,138.88,inrange,ease
4,31/5/2001,2.76,1.5,87.16,139.49,inrange,ease
...,...,...,...,...,...,...,...
277,29/2/2024,-0.77,2.5,118.51,718.27,outrrange,tight
278,31/3/2024,-0.47,2.5,118.11,711.58,outrrange,tight
279,30/4/2024,0.19,2.5,116.80,695.69,outrrange,tight
280,31/5/2024,1.54,2.5,117.21,702.68,inrange,tight
281,30/6/2024,1.54,2.5,117.55,702.68,inrange,tight

### Excel

In [4]:
import pandas as pd
# Also require installing openpyxl

In [5]:
df = pd.read_excel('data/us_indicators.xlsx', sheet_name='Sheet1')

In [6]:
df

,date,cpi,policy_rate,neer,money_supply,inflation_target,type_of_monetary_policy
0,2001-01-31,1.32,1.5,89.24,147.07,inrange,ease
1,2001-02-28,1.44,1.5,90.47,145.49,inrange,ease
2,2001-03-31,1.44,1.5,89.33,140.02,inrange,ease
3,2001-04-30,2.52,1.5,87.32,138.88,inrange,ease
4,2001-05-31,2.76,1.5,87.16,139.49,inrange,ease
...,...,...,...,...,...,...,...
277,2024-02-29,-0.77,2.5,118.51,718.27,outrrange,tight
278,2024-03-31,-0.47,2.5,118.11,711.58,outrrange,tight
279,2024-04-30,0.19,2.5,116.80,695.69,outrrange,tight
280,2024-05-31,1.54,2.5,117.21,702.68,inrange,tight
281,2024-06-30,1.54,2.5,117.55,702.68,inrange,tight

### Database

In [7]:
import sqlite3
import pandas as pd

In [8]:
# Create connection to database
conn = sqlite3.connect(database='data/data.db')

In [9]:
# Set query command
query = 'SELECT date, cpi, policy_rate, neer, money_supply FROM us_indicators'

In [10]:
df = pd.read_sql_query(query, conn)

In [11]:
# Close connection
conn.close()

In [12]:
df

          date   cpi  policy_rate    neer  money_supply
0         date   cpi  policy_rate    neer  money_supply
1    31/1/2001  1.32          1.5   89.24        147.07
2    28/2/2001  1.44          1.5   90.47        145.49
3    31/3/2001  1.44          1.5   89.33        140.02
4    30/4/2001  2.52          1.5   87.32        138.88
..         ...   ...          ...     ...           ...
278  29/2/2024 -0.77          2.5  118.51        718.27
279  31/3/2024 -0.47          2.5  118.11        711.58
280  30/4/2024  0.19          2.5   116.8        695.69
281  31/5/2024  1.54          2.5  117.21        702.68
282  30/6/2024  1.54          2.5  117.55        702.68

[283 rows x 5 columns]

### JSON

In [13]:
import json
import pandas as pd

In [14]:
# Load JSON file as dictionary

with open('data/us_indicators.json') as file:
    data = json.load(file)

In [15]:
data

[{'date': '31/1/2001',
  'cpi': 1.32,
  'policy_rate': 1.5,
  'neer': 89.24,
  'money_supply': 147.07,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '28/2/2001',
  'cpi': 1.44,
  'policy_rate': 1.5,
  'neer': 90.47,
  'money_supply': 145.49,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/3/2001',
  'cpi': 1.44,
  'policy_rate': 1.5,
  'neer': 89.33,
  'money_supply': 140.02,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/4/2001',
  'cpi': 2.52,
  'policy_rate': 1.5,
  'neer': 87.32,
  'money_supply': 138.88,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/5/2001',
  'cpi': 2.76,
  'policy_rate': 1.5,
  'neer': 87.16,
  'money_supply': 139.49,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/6/2001',
  'cpi': 2.15,
  'policy_rate': 2.5,
  'neer': 88.3,
  'money_supply': 139.53,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/7/2001',
  'cpi': 2.03,
  'policy_rate': 2.5,
  'neer': 87.81,
  'money_supply': 138.87,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/8/2001',
  'cpi': 1.43,
  'policy_rate': 2.5,
  'neer': 87.32,
  'money_supply': 144.93,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/9/2001',
  'cpi': 1.3,
  'policy_rate': 2.5,
  'neer': 88.12,
  'money_supply': 144.44,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/10/2001',
  'cpi': 1.32,
  'policy_rate': 2.5,
  'neer': 88.26,
  'money_supply': 144.56,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/11/2001',
  'cpi': 0.96,
  'policy_rate': 2.5,
  'neer': 89.42,
  'money_supply': 148.71,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/12/2001',
  'cpi': 0.72,
  'policy_rate': 2.25,
  'neer': 91.11,
  'money_supply': 148.43,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/1/2002',
  'cpi': 0.84,
  'policy_rate': 2.0,
  'neer': 91.88,
  'money_supply': 147.27,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '28/2/2002',
  'cpi': 0.36,
  'policy_rate': 2.0,
  'neer': 92.56,
  'money_supply': 149.9,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/3/2002',
  'cpi': 0.6,
  'policy_rate': 2.0,
  'neer': 92.89,
  'money_supply': 150.91,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/4/2002',
  'cpi': 0.47,
  'policy_rate': 2.0,
  'neer': 92.36,
  'money_supply': 152.66,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/5/2002',
  'cpi': 0.24,
  'policy_rate': 2.0,
  'neer': 92.02,
  'money_supply': 155.95,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/6/2002',
  'cpi': 0.36,
  'policy_rate': 2.0,
  'neer': 92.03,
  'money_supply': 158.75,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/7/2002',
  'cpi': 0.24,
  'policy_rate': 2.0,
  'neer': 92.41,
  'money_supply': 157.59,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/8/2002',
  'cpi': 0.36,
  'policy_rate': 2.0,
  'neer': 91.03,
  'money_supply': 159.25,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/9/2002',
  'cpi': 0.47,
  'policy_rate': 2.0,
  'neer': 90.0,
  'money_supply': 149.61,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/10/2002',
  'cpi': 1.53,
  'policy_rate': 2.0,
  'neer': 88.9,
  'money_supply': 150.47,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/11/2002',
  'cpi': 1.3,
  'policy_rate': 1.75,
  'neer': 88.67,
  'money_supply': 151.77,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/12/2002',
  'cpi': 1.66,
  'policy_rate': 1.75,
  'neer': 88.31,
  'money_supply': 154.13,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/1/2003',
  'cpi': 2.24,
  'policy_rate': 1.75,
  'neer': 88.18,
  'money_supply': 157.04,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '28/2/2003',
  'cpi': 2.0,
  'policy_rate': 1.75,
  'neer': 87.85,
  'money_supply': 157.63,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/3/2003',
  'cpi': 1.75,
  'policy_rate': 1.75,
  'neer': 88.08,
  'money_supply': 157.89,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/4/2003',
  'cpi': 1.52,
  'policy_rate': 1.75,
  'neer': 87.75,
  'money_supply': 157.73,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/5/2003',
  'cpi': 1.87,
  'policy_rate': 1.75,
  'neer': 87.3,
  'money_supply': 163.36,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/6/2003',
  'cpi': 1.64,
  'policy_rate': 1.25,
  'neer': 88.2,
  'money_supply': 161.57,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/7/2003',
  'cpi': 1.76,
  'policy_rate': 1.25,
  'neer': 88.52,
  'money_supply': 162.57,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/8/2003',
  'cpi': 2.23,
  'policy_rate': 1.25,
  'neer': 89.34,
  'money_supply': 166.53,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/9/2003',
  'cpi': 1.75,
  'policy_rate': 1.25,
  'neer': 91.06,
  'money_supply': 171.74,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/10/2003',
  'cpi': 1.27,
  'policy_rate': 1.25,
  'neer': 90.9,
  'money_supply': 173.17,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/11/2003',
  'cpi': 1.87,
  'policy_rate': 1.25,
  'neer': 90.41,
  'money_supply': 176.32,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/12/2003',
  'cpi': 1.75,
  'policy_rate': 1.25,
  'neer': 89.65,
  'money_supply': 178.24,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/1/2004',
  'cpi': 1.27,
  'policy_rate': 1.25,
  'neer': 90.13,
  'money_supply': 182.21,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '29/2/2004',
  'cpi': 2.2,
  'policy_rate': 1.25,
  'neer': 89.95,
  'money_supply': 183.08,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/3/2004',
  'cpi': 2.44,
  'policy_rate': 1.25,
  'neer': 90.09,
  'money_supply': 183.91,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/4/2004',
  'cpi': 2.53,
  'policy_rate': 1.25,
  'neer': 90.25,
  'money_supply': 182.81,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/5/2004',
  'cpi': 2.4,
  'policy_rate': 1.25,
  'neer': 88.98,
  'money_supply': 180.55,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/6/2004',
  'cpi': 3.11,
  'policy_rate': 1.25,
  'neer': 87.84,
  'money_supply': 177.01,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/7/2004',
  'cpi': 3.23,
  'policy_rate': 1.25,
  'neer': 87.2,
  'money_supply': 177.64,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/8/2004',
  'cpi': 3.09,
  'policy_rate': 1.5,
  'neer': 86.4,
  'money_supply': 176.56,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/9/2004',
  'cpi': 3.55,
  'policy_rate': 1.5,
  'neer': 86.32,
  'money_supply': 178.16,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/10/2004',
  'cpi': 3.43,
  'policy_rate': 1.75,
  'neer': 85.9,
  'money_supply': 180.72,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/11/2004',
  'cpi': 2.97,
  'policy_rate': 1.75,
  'neer': 86.06,
  'money_supply': 189.63,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/12/2004',
  'cpi': 2.97,
  'policy_rate': 2.0,
  'neer': 87.57,
  'money_supply': 192.07,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/1/2005',
  'cpi': 2.75,
  'policy_rate': 2.0,
  'neer': 89.81,
  'money_supply': 195.79,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '28/2/2005',
  'cpi': 2.48,
  'policy_rate': 2.0,
  'neer': 90.58,
  'money_supply': 198.82,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/3/2005',
  'cpi': 3.16,
  'policy_rate': 2.25,
  'neer': 90.02,
  'money_supply': 193.38,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/4/2005',
  'cpi': 3.49,
  'policy_rate': 2.25,
  'neer': 88.61,
  'money_supply': 192.0,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/5/2005',
  'cpi': 3.82,
  'policy_rate': 2.25,
  'neer': 88.07,
  'money_supply': 186.79,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/6/2005',
  'cpi': 3.79,
  'policy_rate': 2.5,
  'neer': 86.76,
  'money_supply': 182.5,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/7/2005',
  'cpi': 5.35,
  'policy_rate': 2.75,
  'neer': 85.84,
  'money_supply': 182.89,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/8/2005',
  'cpi': 5.55,
  'policy_rate': 2.75,
  'neer': 86.22,
  'money_supply': 186.03,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/9/2005',
  'cpi': 5.98,
  'policy_rate': 3.25,
  'neer': 86.71,
  'money_supply': 188.57,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/10/2005',
  'cpi': 6.32,
  'policy_rate': 3.75,
  'neer': 87.94,
  'money_supply': 190.08,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/11/2005',
  'cpi': 5.89,
  'policy_rate': 3.75,
  'neer': 88.29,
  'money_supply': 191.14,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/12/2005',
  'cpi': 5.78,
  'policy_rate': 4.0,
  'neer': 87.97,
  'money_supply': 193.29,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/1/2006',
  'cpi': 5.88,
  'policy_rate': 4.25,
  'neer': 89.9,
  'money_supply': 208.5,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '28/2/2006',
  'cpi': 5.52,
  'policy_rate': 4.25,
  'neer': 90.67,
  'money_supply': 208.32,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/3/2006',
  'cpi': 5.69,
  'policy_rate': 4.5,
  'neer': 91.52,
  'money_supply': 211.35,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/4/2006',
  'cpi': 6.08,
  'policy_rate': 4.75,
  'neer': 93.13,
  'money_supply': 220.72,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/5/2006',
  'cpi': 6.14,
  'policy_rate': 4.75,
  'neer': 91.45,
  'money_supply': 219.05,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/6/2006',
  'cpi': 5.92,
  'policy_rate': 5.0,
  'neer': 91.77,
  'money_supply': 215.99,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/7/2006',
  'cpi': 4.45,
  'policy_rate': 5.0,
  'neer': 92.53,
  'money_supply': 220.04,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/8/2006',
  'cpi': 3.79,
  'policy_rate': 5.0,
  'neer': 93.18,
  'money_supply': 223.47,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/9/2006',
  'cpi': 2.72,
  'policy_rate': 5.0,
  'neer': 93.94,
  'money_supply': 223.69,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/10/2006',
  'cpi': 2.81,
  'policy_rate': 5.0,
  'neer': 94.52,
  'money_supply': 229.83,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/11/2006',
  'cpi': 3.46,
  'policy_rate': 5.0,
  'neer': 95.6,
  'money_supply': 239.0,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/12/2006',
  'cpi': 3.57,
  'policy_rate': 5.0,
  'neer': 96.63,
  'money_supply': 237.65,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/1/2007',
  'cpi': 3.02,
  'policy_rate': 4.75,
  'neer': 96.92,
  'money_supply': 242.37,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '28/2/2007',
  'cpi': 2.46,
  'policy_rate': 4.5,
  'neer': 97.37,
  'money_supply': 248.37,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/3/2007',
  'cpi': 1.97,
  'policy_rate': 4.5,
  'neer': 98.6,
  'money_supply': 253.86,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/4/2007',
  'cpi': 1.86,
  'policy_rate': 4.0,
  'neer': 98.43,
  'money_supply': 257.31,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/5/2007',
  'cpi': 1.94,
  'policy_rate': 3.5,
  'neer': 99.03,
  'money_supply': 260.46,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/6/2007',
  'cpi': 1.94,
  'policy_rate': 3.5,
  'neer': 99.42,
  'money_supply': 258.01,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/7/2007',
  'cpi': 1.73,
  'policy_rate': 3.25,
  'neer': 101.04,
  'money_supply': 266.82,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/8/2007',
  'cpi': 1.16,
  'policy_rate': 3.25,
  'neer': 99.61,
  'money_supply': 262.5,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/9/2007',
  'cpi': 2.04,
  'policy_rate': 3.25,
  'neer': 98.52,
  'money_supply': 262.22,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/10/2007',
  'cpi': 2.53,
  'policy_rate': 3.25,
  'neer': 97.47,
  'money_supply': 266.07,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/11/2007',
  'cpi': 3.09,
  'policy_rate': 3.25,
  'neer': 96.77,
  'money_supply': 267.81,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/12/2007',
  'cpi': 3.09,
  'policy_rate': 3.25,
  'neer': 97.86,
  'money_supply': 270.43,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/1/2008',
  'cpi': 4.33,
  'policy_rate': 3.25,
  'neer': 98.06,
  'money_supply': 278.27,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '29/2/2008',
  'cpi': 5.38,
  'policy_rate': 3.25,
  'neer': 99.17,
  'money_supply': 296.21,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/3/2008',
  'cpi': 5.35,
  'policy_rate': 3.25,
  'neer': 100.51,
  'money_supply': 298.91,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/4/2008',
  'cpi': 6.08,
  'policy_rate': 3.25,
  'neer': 99.94,
  'money_supply': 297.96,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/5/2008',
  'cpi': 7.6,
  'policy_rate': 3.25,
  'neer': 99.1,
  'money_supply': 290.81,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/6/2008',
  'cpi': 8.72,
  'policy_rate': 3.25,
  'neer': 96.3,
  'money_supply': 277.83,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/7/2008',
  'cpi': 9.16,
  'policy_rate': 3.5,
  'neer': 94.92,
  'money_supply': 276.27,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/8/2008',
  'cpi': 6.52,
  'policy_rate': 3.75,
  'neer': 95.97,
  'money_supply': 274.81,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/9/2008',
  'cpi': 6.03,
  'policy_rate': 3.75,
  'neer': 96.37,
  'money_supply': 278.2,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/10/2008',
  'cpi': 3.88,
  'policy_rate': 3.75,
  'neer': 98.49,
  'money_supply': 272.09,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '30/11/2008',
  'cpi': 2.09,
  'policy_rate': 3.75,
  'neer': 98.41,
  'money_supply': 274.23,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/12/2008',
  'cpi': 0.44,
  'policy_rate': 2.75,
  'neer': 96.45,
  'money_supply': 286.35,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '31/1/2009',
  'cpi': -0.48,
  'policy_rate': 2.0,
  'neer': 97.22,
  'money_supply': 287.25,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'tight'},
 {'date': '28/2/2009',
  'cpi': -0.12,
  'policy_rate': 1.5,
  'neer': 97.97,
  'money_supply': 282.11,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/3/2009',
  'cpi': -0.24,
  'policy_rate': 1.5,
  'neer': 97.62,
  'money_supply': 288.33,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/4/2009',
  'cpi': -0.93,
  'policy_rate': 1.25,
  'neer': 97.14,
  'money_supply': 291.01,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/5/2009',
  'cpi': -3.4,
  'policy_rate': 1.25,
  'neer': 97.07,
  'money_supply': 300.03,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/6/2009',
  'cpi': -3.93,
  'policy_rate': 1.25,
  'neer': 97.5,
  'money_supply': 297.26,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/7/2009',
  'cpi': -4.36,
  'policy_rate': 1.25,
  'neer': 97.32,
  'money_supply': 294.04,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/8/2009',
  'cpi': -1.15,
  'policy_rate': 1.25,
  'neer': 96.89,
  'money_supply': 297.15,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/9/2009',
  'cpi': -1.03,
  'policy_rate': 1.25,
  'neer': 96.18,
  'money_supply': 302.32,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/10/2009',
  'cpi': 0.35,
  'policy_rate': 1.25,
  'neer': 95.97,
  'money_supply': 304.52,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/11/2009',
  'cpi': 1.88,
  'policy_rate': 1.25,
  'neer': 95.84,
  'money_supply': 311.37,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/12/2009',
  'cpi': 3.47,
  'policy_rate': 1.25,
  'neer': 96.64,
  'money_supply': 317.97,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/1/2010',
  'cpi': 4.1,
  'policy_rate': 1.25,
  'neer': 97.4,
  'money_supply': 319.49,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '28/2/2010',
  'cpi': 3.68,
  'policy_rate': 1.25,
  'neer': 98.01,
  'money_supply': 323.48,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/3/2010',
  'cpi': 3.42,
  'policy_rate': 1.25,
  'neer': 99.54,
  'money_supply': 335.62,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/4/2010',
  'cpi': 2.97,
  'policy_rate': 1.25,
  'neer': 100.22,
  'money_supply': 334.93,
  'inflation_target': 'inrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '31/5/2010',
  'cpi': 3.41,
  'policy_rate': 1.25,
  'neer': 101.54,
  'money_supply': 338.4,
  'inflation_target': 'outrrange',
  'type_of_monetary_policy': 'ease'},
 {'date': '30/6/2010',
  'cpi': 3.32,
  'policy_rate': 1.25,

In [16]:
df = pd.DataFrame(data)

In [17]:
df

,date,cpi,policy_rate,neer,money_supply,inflation_target,type_of_monetary_policy
0,31/1/2001,1.32,1.5,89.24,147.07,inrange,ease
1,28/2/2001,1.44,1.5,90.47,145.49,inrange,ease
2,31/3/2001,1.44,1.5,89.33,140.02,inrange,ease
3,30/4/2001,2.52,1.5,87.32,138.88,inrange,ease
4,31/5/2001,2.76,1.5,87.16,139.49,inrange,ease
...,...,...,...,...,...,...,...
277,29/2/2024,-0.77,2.5,118.51,718.27,outrrange,tight
278,31/3/2024,-0.47,2.5,118.11,711.58,outrrange,tight
279,30/4/2024,0.19,2.5,116.80,695.69,outrrange,tight
280,31/5/2024,1.54,2.5,117.21,702.68,inrange,tight
281,30/6/2024,1.54,2.5,117.55,702.68,inrange,tight

### API

Get data from https://fred.stlouisfed.org/docs/api/fred/

In [18]:
import requests

In [19]:
api_key = '5fd98b97565288c4cecea09d41f7a4ea'
target_series = 'GNPCA'

In [20]:
url = 'https://api.stlouisfed.org/fred/series/observations'

params = {
    'series_id': target_series,
    'api_key': api_key,
    'file_type': 'json'
}

In [21]:
response = requests.get(url, params=params)

In [22]:
# Check if the request was successful
if response.status_code == 200:
    # Load response as dictionary
    data = response.json()
else:
    # If request was not successful, print reason
    print(f"Error: {response.status_code}")

In [23]:
data

{'realtime_start': '2024-10-04',
 'realtime_end': '2024-10-04',
 'observation_start': '1600-01-01',
 'observation_end': '9999-12-31',
 'units': 'lin',
 'output_type': 1,
 'file_type': 'json',
 'order_by': 'observation_date',
 'sort_order': 'asc',
 'count': 95,
 'offset': 0,
 'limit': 100000,
 'observations': [{'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1929-01-01',
   'value': '1202.659'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1930-01-01',
   'value': '1100.67'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1931-01-01',
   'value': '1029.038'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1932-01-01',
   'value': '895.802'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1933-01-01',
   'value': '883.847'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1934-01-01',
   'value': '978.188'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1935-01-01',
   'value': '1065.716'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1936-01-01',
   'value': '1201.443'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1937-01-01',
   'value': '1264.393'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1938-01-01',
   'value': '1222.966'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1939-01-01',
   'value': '1320.924'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1940-01-01',
   'value': '1435.656'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1941-01-01',
   'value': '1690.844'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1942-01-01',
   'value': '2008.853'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1943-01-01',
   'value': '2349.125'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1944-01-01',
   'value': '2535.744'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1945-01-01',
   'value': '2509.982'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1946-01-01',
   'value': '2221.51'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1947-01-01',
   'value': '2199.313'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1948-01-01',
   'value': '2291.804'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1949-01-01',
   'value': '2277.883'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1950-01-01',
   'value': '2476.097'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1951-01-01',
   'value': '2677.414'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1952-01-01',
   'value': '2786.602'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1953-01-01',
   'value': '2915.598'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1954-01-01',
   'value': '2900.038'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1955-01-01',
   'value': '3107.796'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1956-01-01',
   'value': '3175.622'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1957-01-01',
   'value': '3243.263'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1958-01-01',
   'value': '3215.954'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1959-01-01',
   'value': '3438.007'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1960-01-01',
   'value': '3527.996'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1961-01-01',
   'value': '3620.292'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1962-01-01',
   'value': '3843.844'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1963-01-01',
   'value': '4012.113'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1964-01-01',
   'value': '4243.962'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1965-01-01',
   'value': '4519.102'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1966-01-01',
   'value': '4812.8'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1967-01-01',
   'value': '4944.919'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1968-01-01',
   'value': '5188.802'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1969-01-01',
   'value': '5348.589'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1970-01-01',
   'value': '5358.035'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1971-01-01',
   'value': '5537.202'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1972-01-01',
   'value': '5829.057'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1973-01-01',
   'value': '6170.549'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1974-01-01',
   'value': '6145.506'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1975-01-01',
   'value': '6118.231'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1976-01-01',
   'value': '6454.905'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1977-01-01',
   'value': '6758.055'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1978-01-01',
   'value': '7127.776'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1979-01-01',
   'value': '7375.014'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1980-01-01',
   'value': '7355.39'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1981-01-01',
   'value': '7528.705'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1982-01-01',
   'value': '7397.849'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1983-01-01',
   'value': '7730.794'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1984-01-01',
   'value': '8280.163'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1985-01-01',
   'value': '8598.506'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1986-01-01',
   'value': '8876.436'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1987-01-01',
   'value': '9179.633'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1988-01-01',
   'value': '9569.566'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1989-01-01',
   'value': '9920.542'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1990-01-01',
   'value': '10120.114'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1991-01-01',
   'value': '10100.371'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1992-01-01',
   'value': '10452.604'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1993-01-01',
   'value': '10738.246'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1994-01-01',
   'value': '11155.769'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1995-01-01',
   'value': '11459.835'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1996-01-01',
   'value': '11893.706'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1997-01-01',
   'value': '12408.947'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1998-01-01',
   'value': '12954.457'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '1999-01-01',
   'value': '13583.582'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2000-01-01',
   'value': '14144.962'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2001-01-01',
   'value': '14294.624'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2002-01-01',
   'value': '14529.585'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2003-01-01',
   'value': '14949.293'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2004-01-01',
   'value': '15542.707'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2005-01-01',
   'value': '16075.089'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2006-01-01',
   'value': '16483.539'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2007-01-01',
   'value': '16867.78'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2008-01-01',
   'value': '16940.097'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2009-01-01',
   'value': '16514.062'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2010-01-01',
   'value': '17013.917'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2011-01-01',
   'value': '17306.204'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2012-01-01',
   'value': '17686.281'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2013-01-01',
   'value': '18049.236'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2014-01-01',
   'value': '18499.72'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2015-01-01',
   'value': '19021.225'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2016-01-01',
   'value': '19372.908'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2017-01-01',
   'value': '19905.052'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2018-01-01',
   'value': '20490.925'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2019-01-01',
   'value': '21000.945'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2020-01-01',
   'value': '20482.341'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2021-01-01',
   'value': '21648.657'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2022-01-01',
   'value': '22176.949'},
  {'realtime_start': '2024-10-04',
   'realtime_end': '2024-10-04',
   'date': '2023-01-01',
   'value': '22769.38'}]}

In [24]:
data['observations']

[{'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1929-01-01',
  'value': '1202.659'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1930-01-01',
  'value': '1100.67'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1931-01-01',
  'value': '1029.038'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1932-01-01',
  'value': '895.802'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1933-01-01',
  'value': '883.847'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1934-01-01',
  'value': '978.188'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1935-01-01',
  'value': '1065.716'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1936-01-01',
  'value': '1201.443'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1937-01-01',
  'value': '1264.393'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1938-01-01',
  'value': '1222.966'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1939-01-01',
  'value': '1320.924'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1940-01-01',
  'value': '1435.656'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1941-01-01',
  'value': '1690.844'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1942-01-01',
  'value': '2008.853'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1943-01-01',
  'value': '2349.125'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1944-01-01',
  'value': '2535.744'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1945-01-01',
  'value': '2509.982'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1946-01-01',
  'value': '2221.51'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1947-01-01',
  'value': '2199.313'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1948-01-01',
  'value': '2291.804'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1949-01-01',
  'value': '2277.883'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1950-01-01',
  'value': '2476.097'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1951-01-01',
  'value': '2677.414'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1952-01-01',
  'value': '2786.602'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1953-01-01',
  'value': '2915.598'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1954-01-01',
  'value': '2900.038'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1955-01-01',
  'value': '3107.796'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1956-01-01',
  'value': '3175.622'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1957-01-01',
  'value': '3243.263'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1958-01-01',
  'value': '3215.954'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1959-01-01',
  'value': '3438.007'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1960-01-01',
  'value': '3527.996'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1961-01-01',
  'value': '3620.292'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1962-01-01',
  'value': '3843.844'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1963-01-01',
  'value': '4012.113'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1964-01-01',
  'value': '4243.962'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1965-01-01',
  'value': '4519.102'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1966-01-01',
  'value': '4812.8'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1967-01-01',
  'value': '4944.919'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1968-01-01',
  'value': '5188.802'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1969-01-01',
  'value': '5348.589'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1970-01-01',
  'value': '5358.035'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1971-01-01',
  'value': '5537.202'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1972-01-01',
  'value': '5829.057'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1973-01-01',
  'value': '6170.549'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1974-01-01',
  'value': '6145.506'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1975-01-01',
  'value': '6118.231'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1976-01-01',
  'value': '6454.905'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1977-01-01',
  'value': '6758.055'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1978-01-01',
  'value': '7127.776'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1979-01-01',
  'value': '7375.014'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1980-01-01',
  'value': '7355.39'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1981-01-01',
  'value': '7528.705'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1982-01-01',
  'value': '7397.849'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1983-01-01',
  'value': '7730.794'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1984-01-01',
  'value': '8280.163'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1985-01-01',
  'value': '8598.506'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1986-01-01',
  'value': '8876.436'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1987-01-01',
  'value': '9179.633'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1988-01-01',
  'value': '9569.566'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1989-01-01',
  'value': '9920.542'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1990-01-01',
  'value': '10120.114'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1991-01-01',
  'value': '10100.371'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1992-01-01',
  'value': '10452.604'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1993-01-01',
  'value': '10738.246'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1994-01-01',
  'value': '11155.769'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1995-01-01',
  'value': '11459.835'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1996-01-01',
  'value': '11893.706'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1997-01-01',
  'value': '12408.947'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1998-01-01',
  'value': '12954.457'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '1999-01-01',
  'value': '13583.582'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2000-01-01',
  'value': '14144.962'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2001-01-01',
  'value': '14294.624'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2002-01-01',
  'value': '14529.585'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2003-01-01',
  'value': '14949.293'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2004-01-01',
  'value': '15542.707'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2005-01-01',
  'value': '16075.089'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2006-01-01',
  'value': '16483.539'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2007-01-01',
  'value': '16867.78'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2008-01-01',
  'value': '16940.097'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2009-01-01',
  'value': '16514.062'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2010-01-01',
  'value': '17013.917'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2011-01-01',
  'value': '17306.204'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2012-01-01',
  'value': '17686.281'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2013-01-01',
  'value': '18049.236'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2014-01-01',
  'value': '18499.72'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2015-01-01',
  'value': '19021.225'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2016-01-01',
  'value': '19372.908'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2017-01-01',
  'value': '19905.052'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2018-01-01',
  'value': '20490.925'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2019-01-01',
  'value': '21000.945'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2020-01-01',
  'value': '20482.341'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2021-01-01',
  'value': '21648.657'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2022-01-01',
  'value': '22176.949'},
 {'realtime_start': '2024-10-04',
  'realtime_end': '2024-10-04',
  'date': '2023-01-01',
  'value': '22769.38'}]

In [25]:
df = pd.DataFrame(data['observations'])

In [26]:
df

   realtime_start realtime_end        date      value
0      2024-10-04   2024-10-04  1929-01-01   1202.659
1      2024-10-04   2024-10-04  1930-01-01    1100.67
2      2024-10-04   2024-10-04  1931-01-01   1029.038
3      2024-10-04   2024-10-04  1932-01-01    895.802
4      2024-10-04   2024-10-04  1933-01-01    883.847
..            ...          ...         ...        ...
90     2024-10-04   2024-10-04  2019-01-01  21000.945
91     2024-10-04   2024-10-04  2020-01-01  20482.341
92     2024-10-04   2024-10-04  2021-01-01  21648.657
93     2024-10-04   2024-10-04  2022-01-01  22176.949
94     2024-10-04   2024-10-04  2023-01-01   22769.38

[95 rows x 4 columns]

### Web Scraping

Web scraping is not recommended as it often violates the terms of use for many websites.  
Whenever possible, use an API.

#### Table

Get data from https://en.wikipedia.org/wiki/List_of_Nobel_laureates_in_Physics

In [27]:
import pandas as pd
# Also require installing lxml

In [28]:
url = 'https://en.wikipedia.org/wiki/List_of_Nobel_laureates_in_Physics'

In [29]:
# Get response
response = pd.read_html(url)

In [30]:
response

[     Year Image                  Laureate[a]          Country  \
 0    1901   NaN  Wilhelm RÃ¶ntgen (1845â€“1923)    German Empire
 1    1902   NaN  Hendrik Lorentz (1853â€“1928)      Netherlands
 2    1902   NaN    Pieter Zeeman (1865â€“1943)      Netherlands
 3    1903   NaN  Henri Becquerel (1852â€“1908)           France
 4    1903   NaN     Pierre Curie (1859â€“1906)           France
 ..    ...   ...                          ...              ...
 226  2022   NaN       John Clauser (b. 1942)    United States
 227  2022   NaN    Anton Zeilinger (b. 1945)          Austria
 228  2023   NaN    Anne L'Huillier (b. 1958)    FranceÂ Sweden
 229  2023   NaN      Ferenc Krausz (b. 1962)  AustriaÂ Hungary
 230  2023   NaN    Pierre Agostini (b. 1941)           France

                                           Rationale[b]    Ref
 0    "in recognition of the extraordinary services ...   [19]
 1    "in recognition of the extraordinary service t...   [20]
 2    "in recognition of the extraordinary service t...   [20]
 3     "for his discovery of spontaneous radioactivity"   [21]
 4    "for their joint researches on the radiation p...   [21]
 ..                                                 ...    ...
 226  "for experiments with entangled photons, estab...  [126]
 227  "for experiments with entangled photons, estab...  [126]
 228  "for experimental methods that generate attose...  [127]
 229  "for experimental methods that generate attose...  [127]
 230  "for experimental methods that generate attose...  [127]

 [231 rows x 6 columns],
                           Country  Number of Nobel laureates
 0                   United States                         90
 1                         Germany                         26
 2                  United Kingdom                         24
 3                          France                         16
 4            Russia/Â Soviet Union                         10
 5                     Netherlands                          9
 6                           Japan                          9
 7                          Canada                          6
 8                     Switzerland                          6
 9                         Austria                          5
 10                          Italy                          6
 11                         Sweden                          4
 12                        Denmark                          3
 13  Republic of China (1912â€“1949)                          2
 14                        Hungary                          2
 15     Republic of China (Taiwan)                          2
 16                      Australia                          1
 17                         Norway                          1
 18                         Poland                          1
 19                        Ireland                          1
 20                       Pakistan                          1
 21                        Belgium                          1
 22                          India                          1,
   vteLaureates of the Nobel Prize in Physics  \
 0                                  1901â€“1925
 1                                  1926â€“1950
 2                                  1951â€“1975
 3                                  1976â€“2000
 4                              2001â€“ present

         vteLaureates of the Nobel Prize in Physics.1
 0  1901: RÃ¶ntgen 1902: Lorentz / Zeeman 1903: Bec...
 1  1926: Perrin 1927: Compton / C. Wilson 1928: O...
 2  1951: Cockcroft / Walton 1952: Bloch / Purcell...
 3  1976: Richter / Ting 1977: P. W. Anderson / Mo...
 4  2001: Cornell / Ketterle / Wieman 2002: Davis ...  ,
                                       vteNobel Prizes  \
 0          Lists of Nobel laureates Nobel Prize medal
 1                                              Prizes
 2                                           Laureates
 3                                          by subject
 4                                 by population group
 5                        by continent and nationality
 6                                       by university
 7                                            Nominees
 8                                          by subject
 9                                           by groups
 10                                       by Clarivate
 11                                      Organisations
 12                                            Related
 13  1 Nobel Memorial Prize (not one of the origina...

                                     vteNobel Prizes.1  \
 0          Lists of Nobel laureates Nobel Prize medal
 1   Chemistry Economics1 Literature Peace Physics ...
 2   by occupation Heads of state and government by...
 3   Chemistry Economics1 Literature Peace Physics ...
 4   Bengali Black Christian Female Jewish Latin Am...
 5   African Egyptian South African Asian Chinese F...
 6   City University of New York Columbia Universit...
 7   Catholic priests and religious Couples Women b...
 8   Chemistry Economics1 Literature Peace Individu...
 9   Peace AFSC Nobel nominees PRIO Director's Shor...
 10  Female Chemistry Economics1 Physics Physiology...
 11  Nobel Foundation Nobel Committees Chemistry Ec...
 12  Controversies Alfred Nobel BjÃ¶rkborn Manor Nob...
 13  1 Nobel Memorial Prize (not one of the origina...

                                     vteNobel Prizes.2
 0          Lists of Nobel laureates Nobel Prize medal
 1                                                 NaN
 2                                                 NaN
 3                                                 NaN
 4                                                 NaN
 5                                                 NaN
 6                                                 NaN
 7                                                 NaN
 8                                                 NaN
 9                                                 NaN
 10                                                NaN
 11                                                NaN
 12                                                NaN
 13  1 Nobel Memorial Prize (not one of the origina...  ,
                               0  \
 0                    by subject
 1           by population group
 2  by continent and nationality
 3                 by university

                                                    1
 0  Chemistry Economics1 Literature Peace Physics ...
 1  Bengali Black Christian Female Jewish Latin Am...
 2  African Egyptian South African Asian Chinese F...
 3  City University of New York Columbia Universit...  ,
                               0  \
 0  by continent and nationality

                                                    1
 0  African Egyptian South African Asian Chinese F...  ,
             0                                                  1
 0  by subject  Chemistry Economics1 Literature Peace Individu...,
               0                                                  1
 0     by groups  Peace AFSC Nobel nominees PRIO Director's Shor...
 1  by Clarivate  Female Chemistry Economics1 Physics Physiology...,
               0                                                  1
 0  by Clarivate  Female Chemistry Economics1 Physics Physiology...]

In [31]:
df = response[0]

In [32]:
df

,Year,Image,Laureate[a],Country,Rationale[b],Ref
0,1901,NaN,Wilhelm RÃ¶ntgen (1845â€“1923),German Empire,"""in recognition of the extraordinary services ...",[19]
1,1902,NaN,Hendrik Lorentz (1853â€“1928),Netherlands,"""in recognition of the extraordinary service t...",[20]
2,1902,NaN,Pieter Zeeman (1865â€“1943),Netherlands,"""in recognition of the extraordinary service t...",[20]
3,1903,NaN,Henri Becquerel (1852â€“1908),France,"""for his discovery of spontaneous radioactivity""",[21]
4,1903,NaN,Pierre Curie (1859â€“1906),France,"""for their joint researches on the radiation p...",[21]
...,...,...,...,...,...,...
226,2022,NaN,John Clauser (b. 1942),United States,"""for experiments with entangled photons, estab...",[126]
227,2022,NaN,Anton Zeilinger (b. 1945),Austria,"""for experiments with entangled photons, estab...",[126]
228,2023,NaN,Anne L'Huillier (b. 1958),FranceÂ Sweden,"""for experimental methods that generate attose...",[127]
229,2023,NaN,Ferenc Krausz (b. 1962),AustriaÂ Hungary,"""for experimental methods that generate attose...",[127]
230,2023,NaN,Pierre Agostini (b. 1941),France,"""for experimental methods that generate attose...",[127]

#### Text

Get data from http://example.com

In [33]:
import requests
from bs4 import BeautifulSoup

In [34]:
url = 'http://example.com'

In [35]:
# Get response
response = requests.get(url)

In [36]:
# Check if the request was successful
if response.status_code == 200:
    # Parse the HTML content
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Extract the text content
    paragraphs = soup.find_all('p')

    # Create a list to store data
    data = []
    
    # Print the text content
    for paragraph in paragraphs:
        data.append(paragraph.get_text())
else:
    # If request was not successful, print reason
    print(f"Error: {response.status_code}")

In [37]:
data

['This domain is for use in illustrative examples in documents. You may use this\n    domain in literature without prior coordination or asking for permission.',
 'More information...']

### Text file

In [38]:
# Load text line in the file as list

with open('data/fed_meeting.txt', 'r') as file:
    data = file.readlines()

In [39]:
data

['At the latest Federal Open Market Committee (FOMC) meeting, the Federal Reserve decided to keep the federal funds rate unchanged at 5.25%â€“5.50% for the seventh consecutive meeting. The Fed emphasized that it would not consider lowering rates until inflation is consistently moving toward its 2% target. Despite some easing in inflation over the past year, it remains elevated. The Fed continues to reduce its holdings of U.S. Treasury securities and agency mortgage-backed securities. The economic outlook remains uncertain, with the Fed noting that recent economic activity has expanded at a solid pace, job gains remain strong, and the unemployment rate is low. However, inflationary pressures persist, and the Fed remains vigilant regarding inflation risks. Looking forward, the Fed expects to keep rates steady until there is greater confidence that inflation is sustainably moving toward the 2% goal. The Committee also projects that there might be one rate cut later this year and several more in 2025 if economic conditions permit.']

### Picture

In [40]:
import os
from PIL import Image

In [41]:
# Target picture folder
folder_path = 'data/nasdaq'

In [42]:
# Target files in the folder
input_list = os.listdir(folder_path)

In [43]:
input_list

['nasdaq_1d.png', 'nasdaq_1m.png', 'nasdaq_1h.png']

In [44]:
# Create a list to store data
image_list = []

In [45]:
for filename in input_list:
    # Check if a file is picture
    if filename.endswith(".jpg") or filename.endswith(".png"):
        # Create full path to the file
        file_path = os.path.join(folder_path, filename)
        img = Image.open(file_path)
        image_list.append(img)

In [46]:
image_list

[<PIL.PngImagePlugin.PngImageFile image mode=RGBA size=2318x1590>,
 <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=2318x1590>,
 <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=2318x1590>]

In [47]:
image_list[0].show()